// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_microblog`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `logic`, CPU: `12th Gen Intel(R) Core(TM) i5-12400F`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cogno-chain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_microblog
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --template
// _sdk/substrate/.maintain/frame-weight-template.hbs
// --output
// pallets/microblog/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_microblog`.
pub trait WeightInfo {
	fn post_message(s: u32, ) -> Weight;
	fn delete_post() -> Weight;
	fn check_capacity() -> Weight;
	fn force_set_capacity() -> Weight;
}

/// Weights for `pallet_microblog` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CognoGate::PkhOf` (r:1 w:0)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::NextPostId` (r:1 w:1)
	/// Proof: `Microblog::NextPostId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::ByAuthor` (r:1 w:1)
	/// Proof: `Microblog::ByAuthor` (`max_values`: None, `max_size`: Some(80050), added: 82525, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Posts` (r:0 w:1)
	/// Proof: `Microblog::Posts` (`max_values`: None, `max_size`: Some(583), added: 3058, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 512]`.
	fn post_message(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `83515`
		// Minimum execution time: 16_873_000 picoseconds.
		Weight::from_parts(19_130_688, 83515)
			// Standard Error: 17
			.saturating_add(Weight::from_parts(581, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Microblog::Posts` (r:1 w:1)
	/// Proof: `Microblog::Posts` (`max_values`: None, `max_size`: Some(583), added: 3058, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::ByAuthor` (r:1 w:1)
	/// Proof: `Microblog::ByAuthor` (`max_values`: None, `max_size`: Some(80050), added: 82525, mode: `MaxEncodedLen`)
	fn delete_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `83515`
		// Minimum execution time: 15_450_000 picoseconds.
		Weight::from_parts(17_391_000, 83515)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TalkStake::AllowedStake` (r:1 w:0)
	/// Proof: `TalkStake::AllowedStake` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn check_capacity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `229`
		//  Estimated: `3533`
		// Minimum execution time: 14_271_000 picoseconds.
		Weight::from_parts(15_782_000, 3533)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn force_set_capacity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3533`
		// Minimum execution time: 15_004_000 picoseconds.
		Weight::from_parts(17_041_000, 3533)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `CognoGate::PkhOf` (r:1 w:0)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::NextPostId` (r:1 w:1)
	/// Proof: `Microblog::NextPostId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::ByAuthor` (r:1 w:1)
	/// Proof: `Microblog::ByAuthor` (`max_values`: None, `max_size`: Some(80050), added: 82525, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Posts` (r:0 w:1)
	/// Proof: `Microblog::Posts` (`max_values`: None, `max_size`: Some(583), added: 3058, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 512]`.
	fn post_message(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `83515`
		// Minimum execution time: 16_873_000 picoseconds.
		Weight::from_parts(19_130_688, 83515)
			// Standard Error: 17
			.saturating_add(Weight::from_parts(581, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Microblog::Posts` (r:1 w:1)
	/// Proof: `Microblog::Posts` (`max_values`: None, `max_size`: Some(583), added: 3058, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::ByAuthor` (r:1 w:1)
	/// Proof: `Microblog::ByAuthor` (`max_values`: None, `max_size`: Some(80050), added: 82525, mode: `MaxEncodedLen`)
	fn delete_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `83515`
		// Minimum execution time: 15_450_000 picoseconds.
		Weight::from_parts(17_391_000, 83515)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TalkStake::AllowedStake` (r:1 w:0)
	/// Proof: `TalkStake::AllowedStake` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn check_capacity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `229`
		//  Estimated: `3533`
		// Minimum execution time: 14_271_000 picoseconds.
		Weight::from_parts(15_782_000, 3533)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn force_set_capacity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3533`
		// Minimum execution time: 15_004_000 picoseconds.
		Weight::from_parts(17_041_000, 3533)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
