// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_cogno_gate`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `logic`, CPU: `12th Gen Intel(R) Core(TM) i5-12400F`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cogno-chain-node
// benchmark
// pallet
// --runtime
// /tmp/bench.wasm
// --genesis-builder=runtime
// --genesis-builder-preset
// development
// --pallet
// pallet_cogno_gate
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --template
// _sdk/substrate/.maintain/frame-weight-template.hbs
// --output
// pallets/cogno-gate/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_cogno_gate`.
pub trait WeightInfo {
	fn link_identity_signed() -> Weight;
	fn revoke() -> Weight;
	fn revoke_many(n: u32, ) -> Weight;
	fn unlink_stake() -> Weight;
	fn tombstone_stake_cred() -> Weight;
}

/// Weights for `pallet_cogno_gate` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::Tombstoned` (r:1 w:0)
	/// Proof: `CognoGate::Tombstoned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::PkhOf` (r:1 w:1)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:1 w:1)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotOf` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotOf` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotCount` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountAtScanSlot` (r:0 w:1)
	/// Proof: `CognoGate::AccountAtScanSlot` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn link_identity_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `3593`
		// Minimum execution time: 70_744_000 picoseconds.
		Weight::from_parts(76_760_000, 3593)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `CognoGate::PkhOf` (r:1 w:1)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::StakeCredOf` (r:1 w:0)
	/// Proof: `CognoGate::StakeCredOf` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::ObservedRoles` (r:1 w:0)
	/// Proof: `CardanoRoles::ObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotOf` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotOf` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotCount` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::RoleClaimOf` (r:3 w:0)
	/// Proof: `CardanoRoles::RoleClaimOf` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedRoles` (r:0 w:1)
	/// Proof: `CardanoObserver::LastObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::Tombstoned` (r:0 w:1)
	/// Proof: `CognoGate::Tombstoned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountAtScanSlot` (r:0 w:1)
	/// Proof: `CognoGate::AccountAtScanSlot` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:0 w:1)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `459`
		//  Estimated: `8670`
		// Minimum execution time: 45_856_000 picoseconds.
		Weight::from_parts(51_914_000, 8670)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `CognoGate::PkhOf` (r:64 w:64)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::StakeCredOf` (r:64 w:64)
	/// Proof: `CognoGate::StakeCredOf` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::VotingPower` (r:64 w:0)
	/// Proof: `TalkStake::VotingPower` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::ObservedRoles` (r:64 w:0)
	/// Proof: `CardanoRoles::ObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotOf` (r:32 w:64)
	/// Proof: `CognoGate::ScanSlotOf` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotCount` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountAtScanSlot` (r:32 w:64)
	/// Proof: `CognoGate::AccountAtScanSlot` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:64 w:64)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:64 w:64)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::RoleClaimOf` (r:192 w:0)
	/// Proof: `CardanoRoles::RoleClaimOf` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedStake` (r:0 w:64)
	/// Proof: `CardanoObserver::LastObservedStake` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedRoles` (r:0 w:64)
	/// Proof: `CardanoObserver::LastObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::Tombstoned` (r:0 w:64)
	/// Proof: `CognoGate::Tombstoned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOfStakeCred` (r:0 w:64)
	/// Proof: `CognoGate::AccountOfStakeCred` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::TombstonedStakeCred` (r:0 w:64)
	/// Proof: `CognoGate::TombstonedStakeCred` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:0 w:64)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 64]`.
	fn revoke_many(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `529 + n * (465 ±0)`
		//  Estimated: `1775 + n * (7680 ±0)`
		// Minimum execution time: 5_405_000 picoseconds.
		Weight::from_parts(24_771_150, 1775)
			// Standard Error: 59_102
			.saturating_add(Weight::from_parts(53_069_545, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((10_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((12_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 7680).saturating_mul(n.into()))
	}
	/// Storage: `CognoGate::StakeCredOf` (r:1 w:1)
	/// Proof: `CognoGate::StakeCredOf` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::VotingPower` (r:1 w:0)
	/// Proof: `TalkStake::VotingPower` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedStake` (r:0 w:1)
	/// Proof: `CardanoObserver::LastObservedStake` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOfStakeCred` (r:0 w:1)
	/// Proof: `CognoGate::AccountOfStakeCred` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn unlink_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `611`
		//  Estimated: `3541`
		// Minimum execution time: 19_353_000 picoseconds.
		Weight::from_parts(22_115_000, 3541)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `CognoGate::TombstonedStakeCred` (r:0 w:1)
	/// Proof: `CognoGate::TombstonedStakeCred` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn tombstone_stake_cred() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_359_000 picoseconds.
		Weight::from_parts(7_380_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::Tombstoned` (r:1 w:0)
	/// Proof: `CognoGate::Tombstoned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::PkhOf` (r:1 w:1)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:1 w:1)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotOf` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotOf` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotCount` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountAtScanSlot` (r:0 w:1)
	/// Proof: `CognoGate::AccountAtScanSlot` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn link_identity_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `3593`
		// Minimum execution time: 70_744_000 picoseconds.
		Weight::from_parts(76_760_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `CognoGate::PkhOf` (r:1 w:1)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::StakeCredOf` (r:1 w:0)
	/// Proof: `CognoGate::StakeCredOf` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::ObservedRoles` (r:1 w:0)
	/// Proof: `CardanoRoles::ObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotOf` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotOf` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotCount` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:1 w:1)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::RoleClaimOf` (r:3 w:0)
	/// Proof: `CardanoRoles::RoleClaimOf` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedRoles` (r:0 w:1)
	/// Proof: `CardanoObserver::LastObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::Tombstoned` (r:0 w:1)
	/// Proof: `CognoGate::Tombstoned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountAtScanSlot` (r:0 w:1)
	/// Proof: `CognoGate::AccountAtScanSlot` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:0 w:1)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `459`
		//  Estimated: `8670`
		// Minimum execution time: 45_856_000 picoseconds.
		Weight::from_parts(51_914_000, 8670)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `CognoGate::PkhOf` (r:64 w:64)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::StakeCredOf` (r:64 w:64)
	/// Proof: `CognoGate::StakeCredOf` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::VotingPower` (r:64 w:0)
	/// Proof: `TalkStake::VotingPower` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::ObservedRoles` (r:64 w:0)
	/// Proof: `CardanoRoles::ObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotOf` (r:32 w:64)
	/// Proof: `CognoGate::ScanSlotOf` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::ScanSlotCount` (r:1 w:1)
	/// Proof: `CognoGate::ScanSlotCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountAtScanSlot` (r:32 w:64)
	/// Proof: `CognoGate::AccountAtScanSlot` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:64 w:64)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:64 w:64)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CardanoRoles::RoleClaimOf` (r:192 w:0)
	/// Proof: `CardanoRoles::RoleClaimOf` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedStake` (r:0 w:64)
	/// Proof: `CardanoObserver::LastObservedStake` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedRoles` (r:0 w:64)
	/// Proof: `CardanoObserver::LastObservedRoles` (`max_values`: None, `max_size`: Some(1489), added: 3964, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::Tombstoned` (r:0 w:64)
	/// Proof: `CognoGate::Tombstoned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOfStakeCred` (r:0 w:64)
	/// Proof: `CognoGate::AccountOfStakeCred` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::TombstonedStakeCred` (r:0 w:64)
	/// Proof: `CognoGate::TombstonedStakeCred` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:0 w:64)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 64]`.
	fn revoke_many(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `529 + n * (465 ±0)`
		//  Estimated: `1775 + n * (7680 ±0)`
		// Minimum execution time: 5_405_000 picoseconds.
		Weight::from_parts(24_771_150, 1775)
			// Standard Error: 59_102
			.saturating_add(Weight::from_parts(53_069_545, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((10_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((12_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 7680).saturating_mul(n.into()))
	}
	/// Storage: `CognoGate::StakeCredOf` (r:1 w:1)
	/// Proof: `CognoGate::StakeCredOf` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::VotingPower` (r:1 w:0)
	/// Proof: `TalkStake::VotingPower` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedStake` (r:0 w:1)
	/// Proof: `CardanoObserver::LastObservedStake` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOfStakeCred` (r:0 w:1)
	/// Proof: `CognoGate::AccountOfStakeCred` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn unlink_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `611`
		//  Estimated: `3541`
		// Minimum execution time: 19_353_000 picoseconds.
		Weight::from_parts(22_115_000, 3541)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `CognoGate::TombstonedStakeCred` (r:0 w:1)
	/// Proof: `CognoGate::TombstonedStakeCred` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn tombstone_stake_cred() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_359_000 picoseconds.
		Weight::from_parts(7_380_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
