// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_profile`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-21, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `logic`, CPU: `12th Gen Intel(R) Core(TM) i5-12400F`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cogno-chain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_profile
// --extrinsic
// *
// --steps
// 20
// --repeat
// 5
// --wasm-execution
// compiled
// --template
// _sdk/substrate/.maintain/frame-weight-template.hbs
// --output
// pallets/profile/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_profile`.
pub trait WeightInfo {
	fn set_profile() -> Weight;
	fn clear_profile() -> Weight;
	fn pin_post() -> Weight;
	fn unpin_post() -> Weight;
}

/// Weights for `pallet_profile` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CognoGate::PkhOf` (r:1 w:0)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Profile::Profiles` (r:0 w:1)
	/// Proof: `Profile::Profiles` (`max_values`: None, `max_size`: Some(502), added: 2977, mode: `MaxEncodedLen`)
	fn set_profile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3545`
		// Minimum execution time: 12_936_000 picoseconds.
		Weight::from_parts(14_941_000, 3545)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Profile::Profiles` (r:1 w:1)
	/// Proof: `Profile::Profiles` (`max_values`: None, `max_size`: Some(502), added: 2977, mode: `MaxEncodedLen`)
	fn clear_profile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `83`
		//  Estimated: `3967`
		// Minimum execution time: 10_841_000 picoseconds.
		Weight::from_parts(12_391_000, 3967)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `CognoGate::PkhOf` (r:1 w:0)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Profile::PinnedPost` (r:0 w:1)
	/// Proof: `Profile::PinnedPost` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn pin_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3545`
		// Minimum execution time: 12_136_000 picoseconds.
		Weight::from_parts(13_911_000, 3545)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Profile::PinnedPost` (r:1 w:1)
	/// Proof: `Profile::PinnedPost` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unpin_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `87`
		//  Estimated: `3521`
		// Minimum execution time: 10_523_000 picoseconds.
		Weight::from_parts(12_085_000, 3521)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `CognoGate::PkhOf` (r:1 w:0)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Profile::Profiles` (r:0 w:1)
	/// Proof: `Profile::Profiles` (`max_values`: None, `max_size`: Some(502), added: 2977, mode: `MaxEncodedLen`)
	fn set_profile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3545`
		// Minimum execution time: 12_936_000 picoseconds.
		Weight::from_parts(14_941_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Profile::Profiles` (r:1 w:1)
	/// Proof: `Profile::Profiles` (`max_values`: None, `max_size`: Some(502), added: 2977, mode: `MaxEncodedLen`)
	fn clear_profile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `83`
		//  Estimated: `3967`
		// Minimum execution time: 10_841_000 picoseconds.
		Weight::from_parts(12_391_000, 3967)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `CognoGate::PkhOf` (r:1 w:0)
	/// Proof: `CognoGate::PkhOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Profile::PinnedPost` (r:0 w:1)
	/// Proof: `Profile::PinnedPost` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn pin_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3545`
		// Minimum execution time: 12_136_000 picoseconds.
		Weight::from_parts(13_911_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Profile::PinnedPost` (r:1 w:1)
	/// Proof: `Profile::PinnedPost` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unpin_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `87`
		//  Estimated: `3521`
		// Minimum execution time: 10_523_000 picoseconds.
		Weight::from_parts(12_085_000, 3521)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
