// Rust↔JS observation determinism EQUIVALENCE regression — the JS leg.
//   node services/_shared/observation-equivalence.test.mjs
//
// Loads the committed golden fixture (fixtures/observation-equivalence.json, generated by
// gen-equivalence-fixtures.mjs from the canonical observation.mjs spec) and re-derives each case with
// observeAsOf + canonicalHex, asserting it equals the stored golden. This guards the JS side against
// drift: if observation.mjs's output changes, this fails against the committed golden, forcing a
// deliberate `node gen-equivalence-fixtures.mjs` regen + re-commit.
//
// The SAME fixture is re-derived independently by node/src/cardano_observer.rs's
// `rust_matches_js_observation_equivalence_fixture` #[test]. Because both languages assert against the
// one golden, a Rust↔JS divergence (different reduction, sort, or SCALE encoding) fails one of the two
// suites — the cross-language equivalence Midnight's cnight_equivalence.rs provides in a single process.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { observeAsOf, canonicalHex, candidateHex } from "./observation.mjs";
import { isMain } from "./cli.mjs";

let PASS = 0, FAIL = 0;
const ok = (c, m) => { if (c) { PASS++; console.log(`  ✓ ${m}`); } else { FAIL++; console.log(`  ✗ FAIL: ${m}`); } };

function main() {
	console.log("\n== observation Rust↔JS equivalence fixture (JS leg) ==");
	const here = dirname(fileURLToPath(import.meta.url));
	const fixturePath = join(here, "fixtures", "observation-equivalence.json");
	const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));
	ok(Array.isArray(fixture.cases) && fixture.cases.length > 0, `fixture has ${fixture.cases?.length ?? 0} case(s)`);

	for (const c of fixture.cases) {
		const observed = observeAsOf(c.matches, { vaultHash: c.vaultHash, referenceSlot: c.referenceSlot });

		// 1. the reduced entries match the golden (sorted ascending by beacon bytes), value-for-value.
		const gotEntries = [...observed.entries()]
			.map(([hex, lovelace]) => [hex.toLowerCase(), lovelace.toString()])
			.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
		const entriesEqual = JSON.stringify(gotEntries) === JSON.stringify(c.expectedEntries);
		ok(entriesEqual, `case "${c.name}": observed entries == golden (${gotEntries.length} entr${gotEntries.length === 1 ? "y" : "ies"})`);

		// 2. the canonical SCALE-compatible bytes match the golden — the byte-for-byte determinism witness
		//    the Rust port must also reproduce.
		const gotHex = canonicalHex({ referenceSlot: c.referenceSlot, observed });
		ok(gotHex === c.expectedCanonicalHex, `case "${c.name}": canonicalHex == golden`);
		if (gotHex !== c.expectedCanonicalHex) {
			console.log(`      expected ${c.expectedCanonicalHex}`);
			console.log(`      got      ${gotHex}`);
		}

		// 3. the input-commitment PRE-IMAGE (the candidate set the runtime hashes) matches the golden —
		//    the Rust port must reproduce these exact bytes so blake2_256 of them is identical cross-node.
		const gotCandHex = candidateHex(c.matches, { vaultHash: c.vaultHash });
		ok(gotCandHex === c.expectedCandidateHex, `case "${c.name}": candidate pre-image == golden`);
		if (gotCandHex !== c.expectedCandidateHex) {
			console.log(`      expected ${c.expectedCandidateHex}`);
			console.log(`      got      ${gotCandHex}`);
		}
	}

	console.log(`\n== ${PASS} passed, ${FAIL} failed ==`);
	if (FAIL > 0) process.exit(1);
}

if (isMain(import.meta.url)) main();
export { main };
