// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_governance_fuel`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-14, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `logic`, CPU: `12th Gen Intel(R) Core(TM) i5-12400F`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cogno-chain-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/cogno-chain-runtime/cogno_chain_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --pallet
// pallet_governance_fuel
// --extrinsic
// *
// --steps
// 20
// --repeat
// 5
// --wasm-execution
// compiled
// --template
// _sdk/substrate/.maintain/frame-weight-template.hbs
// --output
// pallets/governance-fuel/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_governance_fuel`.
pub trait WeightInfo {
	fn set_allowance() -> Weight;
	fn revoke() -> Weight;
	fn regenerate(n: u32, ) -> Weight;
}

/// Weights for `pallet_governance_fuel` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `GovernanceFuel::Allowances` (r:1 w:1)
	/// Proof: `GovernanceFuel::Allowances` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GovernanceFuel::TotalMinted` (r:1 w:1)
	/// Proof: `GovernanceFuel::TotalMinted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_allowance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `4559`
		// Minimum execution time: 27_970_000 picoseconds.
		Weight::from_parts(32_114_000, 4559)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `GovernanceFuel::Allowances` (r:1 w:1)
	/// Proof: `GovernanceFuel::Allowances` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GovernanceFuel::TotalRevoked` (r:1 w:1)
	/// Proof: `GovernanceFuel::TotalRevoked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `4559`
		// Minimum execution time: 40_290_000 picoseconds.
		Weight::from_parts(45_909_000, 4559)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `GovernanceFuel::Allowances` (r:1 w:0)
	/// Proof: `GovernanceFuel::Allowances` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:64 w:64)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GovernanceFuel::TotalMinted` (r:1 w:1)
	/// Proof: `GovernanceFuel::TotalMinted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 64]`.
	fn regenerate(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211 + n * (51 ±0)`
		//  Estimated: `4559 + n * (2603 ±0)`
		// Minimum execution time: 2_703_000 picoseconds.
		Weight::from_parts(16_028_310, 4559)
			// Standard Error: 11_713
			.saturating_add(Weight::from_parts(18_284_214, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `GovernanceFuel::Allowances` (r:1 w:1)
	/// Proof: `GovernanceFuel::Allowances` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GovernanceFuel::TotalMinted` (r:1 w:1)
	/// Proof: `GovernanceFuel::TotalMinted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_allowance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `4559`
		// Minimum execution time: 27_970_000 picoseconds.
		Weight::from_parts(32_114_000, 4559)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `GovernanceFuel::Allowances` (r:1 w:1)
	/// Proof: `GovernanceFuel::Allowances` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GovernanceFuel::TotalRevoked` (r:1 w:1)
	/// Proof: `GovernanceFuel::TotalRevoked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `4559`
		// Minimum execution time: 40_290_000 picoseconds.
		Weight::from_parts(45_909_000, 4559)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `GovernanceFuel::Allowances` (r:1 w:0)
	/// Proof: `GovernanceFuel::Allowances` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:64 w:64)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GovernanceFuel::TotalMinted` (r:1 w:1)
	/// Proof: `GovernanceFuel::TotalMinted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 64]`.
	fn regenerate(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211 + n * (51 ±0)`
		//  Estimated: `4559 + n * (2603 ±0)`
		// Minimum execution time: 2_703_000 picoseconds.
		Weight::from_parts(16_028_310, 4559)
			// Standard Error: 11_713
			.saturating_add(Weight::from_parts(18_284_214, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
	}
}
