// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_cardano_observer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `logic`, CPU: `12th Gen Intel(R) Core(TM) i5-12400F`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cogno-chain-node
// benchmark
// pallet
// --runtime
// target/release/wbuild/cogno-chain-runtime/cogno_chain_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --pallet
// pallet_cardano_observer
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --template
// _sdk/substrate/.maintain/frame-weight-template.hbs
// --output
// pallets/cardano-observer/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_cardano_observer`.
pub trait WeightInfo {
	fn observe(n: u32, m: u32, p: u32, q: u32, ) -> Weight;
	fn set_enforcement() -> Weight;
}

/// Weights for `pallet_cardano_observer` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CardanoObserver::LastReference` (r:1 w:1)
	/// Proof: `CardanoObserver::LastReference` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::EnforceWeight` (r:1 w:0)
	/// Proof: `CardanoObserver::EnforceWeight` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:1024 w:0)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::AllowedStake` (r:2048 w:2048)
	/// Proof: `TalkStake::AllowedStake` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:2048 w:2048)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObserved` (r:1 w:1)
	/// Proof: `CardanoObserver::LastObserved` (`max_values`: Some(1), `max_size`: Some(65538), added: 66033, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOfStakeCred` (r:1024 w:0)
	/// Proof: `CognoGate::AccountOfStakeCred` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::VotingPower` (r:2048 w:2048)
	/// Proof: `TalkStake::VotingPower` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedStake` (r:1 w:1)
	/// Proof: `CardanoObserver::LastObservedStake` (`max_values`: Some(1), `max_size`: Some(61442), added: 61937, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::Stalled` (r:1 w:0)
	/// Proof: `CardanoObserver::Stalled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastAppliedAt` (r:0 w:1)
	/// Proof: `CardanoObserver::LastAppliedAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 1024]`.
	/// The range of component `m` is `[0, 1024]`.
	/// The range of component `p` is `[0, 1024]`.
	/// The range of component `q` is `[0, 1024]`.
	fn observe(n: u32, m: u32, p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (167 ±0) + n * (245 ±0) + p * (238 ±0) + q * (160 ±0)`
		//  Estimated: `67023 + m * (2551 ±0) + n * (2555 ±0) + p * (2543 ±0) + q * (2539 ±0)`
		// Minimum execution time: 40_430_325_000 picoseconds.
		Weight::from_parts(42_619_202_000, 67023)
			// Standard Error: 269_232
			.saturating_add(Weight::from_parts(12_362_646, 0).saturating_mul(n.into()))
			// Standard Error: 269_232
			.saturating_add(Weight::from_parts(2_612_042, 0).saturating_mul(m.into()))
			// Standard Error: 269_232
			.saturating_add(Weight::from_parts(7_246_199, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(q.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(q.into())))
			.saturating_add(Weight::from_parts(0, 2551).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2555).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 2543).saturating_mul(p.into()))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(q.into()))
	}
	/// Storage: `CardanoObserver::EnforceWeight` (r:0 w:1)
	/// Proof: `CardanoObserver::EnforceWeight` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_enforcement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_710_000 picoseconds.
		Weight::from_parts(5_704_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `CardanoObserver::LastReference` (r:1 w:1)
	/// Proof: `CardanoObserver::LastReference` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::EnforceWeight` (r:1 w:0)
	/// Proof: `CardanoObserver::EnforceWeight` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOf` (r:1024 w:0)
	/// Proof: `CognoGate::AccountOf` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::AllowedStake` (r:2048 w:2048)
	/// Proof: `TalkStake::AllowedStake` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Microblog::Capacity` (r:2048 w:2048)
	/// Proof: `Microblog::Capacity` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObserved` (r:1 w:1)
	/// Proof: `CardanoObserver::LastObserved` (`max_values`: Some(1), `max_size`: Some(65538), added: 66033, mode: `MaxEncodedLen`)
	/// Storage: `CognoGate::AccountOfStakeCred` (r:1024 w:0)
	/// Proof: `CognoGate::AccountOfStakeCred` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `TalkStake::VotingPower` (r:2048 w:2048)
	/// Proof: `TalkStake::VotingPower` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastObservedStake` (r:1 w:1)
	/// Proof: `CardanoObserver::LastObservedStake` (`max_values`: Some(1), `max_size`: Some(61442), added: 61937, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::Stalled` (r:1 w:0)
	/// Proof: `CardanoObserver::Stalled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `CardanoObserver::LastAppliedAt` (r:0 w:1)
	/// Proof: `CardanoObserver::LastAppliedAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 1024]`.
	/// The range of component `m` is `[0, 1024]`.
	/// The range of component `p` is `[0, 1024]`.
	/// The range of component `q` is `[0, 1024]`.
	fn observe(n: u32, m: u32, p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (167 ±0) + n * (245 ±0) + p * (238 ±0) + q * (160 ±0)`
		//  Estimated: `67023 + m * (2551 ±0) + n * (2555 ±0) + p * (2543 ±0) + q * (2539 ±0)`
		// Minimum execution time: 40_430_325_000 picoseconds.
		Weight::from_parts(42_619_202_000, 67023)
			// Standard Error: 269_232
			.saturating_add(Weight::from_parts(12_362_646, 0).saturating_mul(n.into()))
			// Standard Error: 269_232
			.saturating_add(Weight::from_parts(2_612_042, 0).saturating_mul(m.into()))
			// Standard Error: 269_232
			.saturating_add(Weight::from_parts(7_246_199, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(q.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(q.into())))
			.saturating_add(Weight::from_parts(0, 2551).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2555).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 2543).saturating_mul(p.into()))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(q.into()))
	}
	/// Storage: `CardanoObserver::EnforceWeight` (r:0 w:1)
	/// Proof: `CardanoObserver::EnforceWeight` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_enforcement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_710_000 picoseconds.
		Weight::from_parts(5_704_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
