//! `cogno-chain-node` subcommands.
//!
//! Deliberately minimal — like `cardano-node`, the daemon's primary job is `run`. The other operator
//! subcommands are keystore / p2p-key management and exporting/generating a chainspec; benchmarking is a
//! dev/CI tool, present only when built `--features runtime-benchmarks`. The Substrate-template DB/block
//! forensics + recovery commands (build-spec / check-block / export-blocks / import-blocks / export-state /
//! chain-info / purge-chain / revert) are intentionally NOT exposed on the node binary.

#[derive(Debug, clap::Parser)]
// A bare invocation prints the top-level help (cardano-node style) instead of silently starting — the
// node's primary subcommand is `run`.
#[command(arg_required_else_help = true)]
pub struct Cli {
	#[command(subcommand)]
	pub subcommand: Subcommand,
}

#[derive(Debug, clap::Subcommand)]
#[allow(clippy::large_enum_variant)]
pub enum Subcommand {
	/// Run the node: Aura block authoring, GRANDPA finality, and the live Cardano-observation inherent.
	Run(sc_cli::RunCmd),

	/// Keystore + p2p-key management: `insert` a session secret from a `cogno-chain-cli key gen` key FILE,
	/// and `inspect-node-key` (the libp2p network identity). Session keys are GENERATED by the CLI.
	#[command(subcommand)]
	Key(crate::key::KeyCmd),

	/// Export the chain specification for a `--chain` network (operator-keyed genesis lives here).
	ExportChainSpec(sc_cli::ExportChainSpecCmd),

	/// Generate an OPERATOR-KEYED chain spec from `cogno-chain-cli key gen` key FILES: seats the validator
	/// authority + committee + session keys from real keys (refuses well-known dev keys). Writes a plain +
	/// a raw spec; the raw one is what the node runs with `--chain`.
	#[command(name = "gen-chainspec")]
	GenChainSpec(crate::gen_chainspec::GenChainSpecCmd),

	/// Runtime/extrinsic benchmarking (dev/CI weight generation). Only built with
	/// `--features runtime-benchmarks`.
	#[cfg(feature = "runtime-benchmarks")]
	#[command(subcommand)]
	Benchmark(frame_benchmarking_cli::BenchmarkCmd),
}
